project:
  type: website
  output-dir: ../docs

website:
  title: "SPRFMO SC Third Squid Workshop (SCW18)"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: documents/SCW18-agenda.qmd
        text: Agenda
      - href: SCW18-squid3_meeting_report.qmd
        text: Report

format:
  html:
    toc: true
    toc-depth: 2
    code-fold: true
